config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'sessions#new'

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :vehicles do   
    resources :maintenance_items
  end 


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/maintenance_item.rb
class MaintenanceItem < ApplicationRecord

    belongs_to :vehicle,
        primary_key: :id, 
        foreign_key: :vehicle_id,
        class_name: :Vehicle

    belongs_to :user

    validates_presence_of :title, :date_preformed, :vehicle_id, :user_id

end 

app/models/user.rb
class User < ApplicationRecord

    validates_presence_of :email, :password_digest, :first_name, :last_name
    validates :email, :session_token, uniqueness: true
    validates :password, length: { minimum: 6, allow_nil: true }

    has_many :vehicles

    attr_reader :password

    after_initialize :ensure_session_token

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        user && user.is_password(password) ? user : nil
    end

    def is_password(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def ensure_session_token
        self.session_token ||= User.generate_session_token
    end

    def self.generate_session_token
        SecureRandom.urlsafe_base64
    end

    def reset_session_token
        self.session_token = User.generate_session_token
        self.save
        self.session_token
    end 

end 

app/models/vehicle.rb
class Vehicle < ApplicationRecord

    validates :year, :make, :model, presence: true

    has_many :maintenance_items

    belongs_to :user
    
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  private

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login(user)
    user.reset_session_token
    session[:session_token] = user.session_token
    @current_user = user
  end

  def logout
    current_user.reset_session_token
    session[:session_token] = nil
  end

  def ensure_logged_in
    unless current_user
      redirect_to root_url
    end
  end


end

app/controllers/maintenance_items_controller.rb
class MaintenanceItemsController < ApplicationController

    before_action :ensure_logged_in


    def index
        @maintenance_items = MaintenanceItem.all
        render :index
    end
    
    def show
        @maintenance_item = MaintenanceItem.find(params[:id])
        @vehicle_id = @maintenance_item.vehicle_id
        @vehicle = Vehicle.find(@vehicle_id)
        render :show
    end     

    def create
        @maintenance_item = MaintenanceItem.new(maintenance_item_params)
        @maintenance_item.user_id = current_user.id
        @maintenance_item.vehicle_id = params[:vehicle_id]
        if @maintenance_item.save
            redirect_to vehicle_url(params[:vehicle_id])
        else
            flash.now[:errors] = @maintenance_item.errors.full_messages
            render :new
        end 
    end     

    def edit
        @maintenance_item = MaintenanceItem.find(params[:id])
        @vehicle_id = @maintenance_item.vehicle_id
        render :edit
    end 

    def update
        @maintenance_item = MaintenanceItem.find(params[:id])
        vehicle_id = @maintenance_item.vehicle_id
        if @maintenance_item.update(maintenance_item_params)
            redirect_to vehicle_url(vehicle_id)
        else 
            flash.now[:errors] = @maintenance_item.errors.full_messages
            render :edit
        end     
    end 

    def destroy
        maintenance_item = MaintenanceItem.find(params[:id])
        vehicle_id = maintenance_item.vehicle_id
        maintenance_item.destroy
        redirect_to vehicle_url(vehicle_id)
    end 

    private
    def maintenance_item_params
        params.require(:maintenance_item).permit(:title, :date_preformed, :comment, :current_mileage, :cost)
    end 

end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
      if current_user
          redirect_to vehicles_url 
      else
          render :new
      end 
  end

  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )
    if user
      login(user)
      redirect_to vehicles_url
    else
      flash.now[:errors] = ['Invalid email or password']
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    

    def new
        if current_user
            redirect_to vehicles_url 
        else
            render :new
        end 
    end
    
    def show
        @user = User.find_by(id: params[:id])
        render :show
    end 
    
    def create  
        @user = User.new(user_params)
        if @user.save
            login(@user)
            redirect_to vehicles_url
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end 
    end 

    def user_params
        params.require(:user).permit(:email, :password, :first_name, :last_name)
    end

end 

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController

    before_action :ensure_logged_in

    def new
        render :new
    end 

    def create
        @vehicle = Vehicle.new(vehicle_params)
        @vehicle.user_id = current_user.id

        if @vehicle.save
            redirect_to vehicles_url
        else
            flash.now[:errors] = @vehicle.errors.full_messages
        end 
    end 

    def index 
    end
    
    def show
        @vehicle = Vehicle.find(params[:id])
        render :show
    end 

    def edit 
        @vehicle = Vehicle.find(params[:id])
        render :edit    
    end 

    def update
        @vehicle = Vehicle.find(params[:id])
        if @vehicle.update(vehicle_params)
            redirect_to vehicle_url(@vehicle)
        else 
            flash.now[:errors] = @vehicle.errors.full_messages
            render :edit
        end 
    end 

    def destroy
        vehicle = Vehicle.find(params[:id]);
        vehicle.destroy 
        redirect_to vehicles_url
    end 

    private
    def vehicle_params
        params.require(:vehicle).permit(:year, :make, :model, :vin, :mileage)
    end 

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if flash[:errors] %>
  <div id="error-modal" class="radius panel large-4 small-4 cell small-centered large-centered callout alert" data-closable>

    <h4>Something went wrong...</h4>

      <% flash[:errors].map do |error| %>
        <div><%= error %></div>
      <% end %>

    <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
      <span aria-hidden="true">&times;</span>
    </button>

  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="navbar grid-x">  

    <!-- left side of navbar -->
    <div class="flex-container text-center align-center small-3 cell">
        <h5 style="margin-bottom: 0;">Welcome, <%= current_user.first_name %>!</h5>
    </div>

    <div class="flex-container text-center align-center small-6 cell">
        <h4 id="garage" style="margin-bottom: 0;">Your Garage</h4>
    </div>

    <!-- right side of navbar -->
    <div class="flex-container text-center align-center small-3 cell">
        <form action="<%= session_url %>" method="POST">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <input type="hidden" name="_method" value="delete">
            <input type="submit" class="button small" value="Sign Out">
        </form>
    </div>

</div>

app/views/layouts/_new_maintenace_form.html.erb
<!----------- Modal to add a new maintenance --------------->
<div class="vehicle-form-wrapper modal" id="serviceModal">
    <form class="vehicle-form" action="<%= vehicle_maintenance_items_url(@vehicle) %>" method="POST">

        <h3>Add Maintenance</h3>

        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

        <label for="title">Title
            <input type="text" name="maintenance_item[title]" value="" id="title" placeholder="Enter Title">
        </label>

        <label for="date_preformed">Date Preformed
            <input type="date" name="maintenance_item[date_preformed]" value="" id="date_preformed" placeholder="Add Date Preformed">
        </label>

        <label for="current_mileage">Current Mileage
            <input type="number" name="maintenance_item[current_mileage]" value="" id="current_mileage" placeholder="Add Current Mileage">
        </label>

        <label for="comment">Comment
            <input type="text" name="maintenance_item[comment]" value="" id="comment" placeholder="Add Comment">
        </label>

        <label for="cost">Cost
            <input type="number" name="maintenance_item[cost]" value="" id="cost" placeholder="Add Cost">
        </label>

        <input type="submit"  class="auth-submit expanded button" value="Add Maintenance">
        
    </form>
</div>

app/views/layouts/_new_vehicle_form.html.erb
<!----------- Form to add a new vehicle --------------->
<div class="vehicle-form-wrapper modal" id="vehicleModal">
    <form class="vehicle-form" action="<%= vehicles_url %>" method="POST">

        <h3>Add A Vehicle</h3>

        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

        <label for="year">Year
            <input type="number" name="vehicle[year]" value="" id="year" placeholder="Enter Year">
        </label>

        <label for="make">Make
            <input type="text" name="vehicle[make]" value="" id="make" placeholder="Enter Make">
        </label>

        <label for="model">Model
            <input type="text" name="vehicle[model]" value="" id="model" placeholder="Enter Model">
        </label>

        <label for="vin">VIN
            <input type="text" name="vehicle[vin]" value="" id="vin" placeholder="Enter VIN">
        </label>

        <label for="mileage">Mileage
            <input type="number" name="vehicle[mileage]" value="" id="mileage" placeholder="Enter Current Mileage">
        </label>

        <input type="submit" class="auth-submit expanded button" value="Add Vehicle">
        
    </form>
</div>

app/views/layouts/_vehicle_tabs.html.erb
<div class="grid-container">
  <div class="grid-x grid-margin-x">

    <div class="cell medium-3">
      <ul class="vertical tabs" data-tabs id="vehicle-tabs">
        <% current_user.vehicles.map do |vehicle| %>
            <li class="my-tabs tabs-title"><a style="font-size: 18px; border-bottom: 1px solid black;" class="tabs-a" href="/vehicles/<%= vehicle.id %>"><%= vehicle.year %> <%= vehicle.make %> <%= vehicle.model %></a>
            </li>
        <% end %>

        <!----------- button to launch modal to add a new vehicle --------------->
        <p class="my-p"><a class="button small" href="#vehicleModal" rel="modal:open">Add Vehicle</a></p>
      </ul>

      
    </div>

    <div class="cell medium-9">
      <div class="tabs-content" data-tabs-content="vehicle-tabs">
        <%= yield %>
      </div>
    </div>
  </div>

</div>

<%= render 'layouts/new_vehicle_form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>The Garage App</title>
    <%= favicon_link_tag asset_path('default-thumbnail.png') %>
    
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/foundation-sites@6.5.1/dist/css/foundation.min.css" integrity="sha256-1mcRjtAxlSjp6XJBgrBeeCORfBp/ppyX4tsvpQVCcpA= sha384-b5S5X654rX3Wo6z5/hnQ4GBmKuIJKMPwrJXn52ypjztlnDK2w9+9hSMBz/asy9Gw sha512-M1VveR2JGzpgWHb0elGqPTltHK3xbvu3Brgjfg4cg5ZNtyyApxw/45yHYsZ/rCVbfoO5MSZxB241wWq642jLtA==" crossorigin="anonymous">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.0.1/js/vendor/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/foundation-sites@6.5.1/dist/js/foundation.min.js" integrity="sha256-WUKHnLrIrx8dew//IpSEmPN/NT3DGAEmIePQYIEJLLs= sha384-53StQWuVbn6figscdDC3xV00aYCPEz3srBdV/QGSXw3f19og3Tq2wTRe0vJqRTEO sha512-X9O+2f1ty1rzBJOC8AXBnuNUdyJg0m8xMKmbt9I3Vu/UOWmSg5zG+dtnje4wAZrKtkopz/PEDClHZ1LXx5IeOw==" crossorigin="anonymous"></script>

    <!-- jQuery Modal -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
    
    <!-- jQuery Autocomplete -->
    <link rel="stylesheet" type="text/css" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/smoothness/jquery-ui.css">

    <script src="https://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>

    <!-- jQuery migrate 3.0 conflicts foundation -->
    <!-- using older migrate version -->
    <script src="https://code.jquery.com/jquery-migrate-1.4.1.min.js"></script> 

    <script>
      console.log(`
    __  ___ ___    ______
   /  |/  //   |  / ____/
  / /|_/ // /| | / /     
 / /  / // ___ |/ /___   
/_/  /_//_/  |_|\____/   
                         
          `)
    </script>
    
  </head>

  <body>
 
    <div class="main">

      <% if logged_in? %>

        <%= render 'layouts/navbar' %>
        <%= render 'layouts/vehicle_tabs' %>

      <% else %> 

        <div>
          <%= yield %>
        </div>

      <% end %>

    </div>
  </body>
</html>

app/views/maintenance_items/edit.html.erb
<div class="grid-container">

    <div class="grid-x">
        <div class="large-6 large-offset-3 medium-8 medium-offset-2 small-10 small-offset-1 cell">
            <form class="vehicle-form" action="<%= vehicle_maintenance_item_url(@vehicle_id, @maintenance_item) %>" method="POST">

                <h4 class="my-h4"><%= @maintenance_item.title %></h4>

                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                <input type="hidden" name="_method" value="PATCH">

                <label for="title">Title
                    <input type="text" name="maintenance_item[title]" value="<%= @maintenance_item.title %>" id="title" placeholder="Enter Title">
                </label>

                <label for="date_preformed">Date Preformed
                    <input type="date" name="maintenance_item[date_preformed]" value="<%= @maintenance_item.date_preformed %>" id="date_preformed" placeholder="Add Date Preformed">
                </label>

                <label for="current_mileage">Current Mileage
                    <input type="number" name="maintenance_item[current_mileage]" value="<%= @maintenance_item.current_mileage %>" id="current_mileage" placeholder="Add Current Mileage">
                </label>

                <label for="comment">Comment
                    <input type="text" name="maintenance_item[comment]" value="<%= @maintenance_item.comment %>" id="comment" placeholder="Add Comment">
                </label>

                <label for="cost">Cost
                    <input type="number" name="maintenance_item[cost]" value="<%= @maintenance_item.cost %>" id="cost" placeholder="Add Cost">
                </label>

                <input type="submit" class="button expanded" value="Update">

            </form>

        <div class="back-button-wrapper">
            <a class="button small" href="/vehicles/<%= @vehicle_id %>">Back</a>
        </div>

        </div>
    </div>
</div>

app/views/maintenance_items/show.html.erb
<div class="information-container">
    
    <h2 class="auth-h2">
        <%= @vehicle.year %> <%= @vehicle.make %> <%= @vehicle.model %>
    </h2>
    
    <h3 class="auth-h2" style="margin-bottom: 3%;">
        <%= @maintenance_item.title %>
    </h3>

    <div class="information-row">    
        Date: <%= @maintenance_item.date_preformed %>
    </div>

    <div class="information-row">    
        Mileage: <%= @maintenance_item.current_mileage %>
    </div>

    <div class="information-row">    
        Cost: $<%= @maintenance_item.cost %>
    </div>

    <div class="information-row">    
        Comment: <%= @maintenance_item.comment %>
    </div>

</div>

<div class="back-button-wrapper">
    <a class="auth-submit back-button button" href="<%= vehicle_url(@vehicle_id) %>">Back</a>
</div>

app/views/users/new.html.erb
<div class="grid-x main" >

    <%= render 'layouts/errors' %>


    <div class="auth-form large-6 large-offset-3 medium-8 medium-offset-2 small-10 small-offset-1 cell">

        <h3 class="auth-h2">Sign Up</h3>

        <form action="<%= users_url %>" method="POST">
        
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

            <label for="email">Email
                <input type="text" name="user[email]" id="email" value="" placeholder="Enter Email Address">
            </label>

            <label for="first_name">First Name
                <input type="text" name="user[first_name]" id="first_name" value="" placeholder="Enter First Name">
            </label>

            <label for="last_name">Last Name
                <input type="text" name="user[last_name]" id="last_name" value="" placeholder="Enter Last Name">
            </label>

            <label for="password">Password
                <input type="password" name="user[password]" id="password" value="" placeholder="Enter a Password">
            </label>

            <input class="auth-submit expanded button" type="submit" value="Sign Up" placeholder="Enter Email Address">

        </form>

        <div class="auth-switch">Already have an account? <a href="<%= new_session_url %>">Log In!</a></div>
    </div>

</div>

app/views/vehicles/edit.html.erb
<div class="grid-container">

    <div class="grid-x">
        <div class="large-6 large-offset-3 medium-8 medium-offset-2 small-10 small-offset-1 cell">
            <form class="vehicle-form" action="<%= vehicle_url(@vehicle) %>" method="POST">

                <h4 class="my-h4"><%= @vehicle.year %> <%= @vehicle.make %> <%= @vehicle.model %></h4>

                <input type="hidden" name="authenticity_token" value= "<%= form_authenticity_token %>">
                <input type="hidden" name="_method" value="PATCH">

                <label for="year">Year
                    <input type="number" name="vehicle[year]" value="<%= @vehicle.year %>" id="year">
                </label>

                <label for="make">Make
                    <input type="text" name="vehicle[make]" value="<%= @vehicle.make %>" id="make">
                </label>

                <label for="model">Model
                    <input type="text" name="vehicle[model]" value="<%= @vehicle.model %>" id="model">
                </label>

                <label for="vin">VIN
                    <input type="text" name="vehicle[vin]" value="<%= @vehicle.vin %>" id="vin">
                </label>

                <label for="mileage">Mileage
                    <input type="number" name="vehicle[mileage]" value="<%= @vehicle.mileage %>" id="mileage">
                </label>

                <input class="button expanded" type="submit" value="Update">
            
            </form>

            <div class="back-button-wrapper">
                <a class="button small" href="/vehicles/<%= @vehicle.id %>">Back</a>
            </div>

        </div>
    </div>
</div>

app/views/vehicles/show.html.erb
<div style="position: relative;">
    <!-- vehicle delete button -->
    <button class="vehicle close-button" aria-label="Close alert" type="button" id="<%= @vehicle.id %>">
        <span aria-hidden="true">&times;</span>
    </button>

    <!-- vehicle edit button -->
    <button class="vehicle edit-button" type="button" id="<%= @vehicle.id %>">
        <span><i class="fas fa-cogs" aria-hidden="true"></i></i></span>
    </button>

    <h2 class="auth-h2" style="padding-top: 0%;"><%= @vehicle.year %> <%= @vehicle.make %> <%= @vehicle.model %></h2>


    <div class='maintenance-items-grid grid-container container-padding-y'>

        <!-- vehicle details header -->
        <div class="grid-x ">
            <div class="service-header flex-container align-center small-6 medium-6 large-6 cell">
                Current Mileage
            </div>

            <div class="service-header flex-container align-center small-6 medium-6 large-6 cell">
                VIN
            </div>
        </div>


        <div class="grid-x">
            <div class="flex-container align-center small-6 medium-6 large-6 cell">
                <div><%= @vehicle.mileage %></div>
            </div>

            <div class="flex-container align-center small-6 medium-6 large-6 cell">
                <div><%= @vehicle.vin %></div>
            </div>

        </div>
    </div>

 
    <!-- Creating list elements for each maintenance item -->
    <div class="maintenance-items-grid grid-container">

        <% unless @vehicle.maintenance_items.empty? %>

        <% end %>

        <!-- listing all maintenance items -->
        <% @vehicle.maintenance_items.map do |maintenance| %>


            <div class="grid-x grid-margin-y">
                <h4 class="my-h4"><%= maintenance.title.capitalize %></h4>
            </div>


            <!-- maintenance items header -->
            <div class="grid-x">

                <div class="service-header small-4 cell">
                    Date
                </div>

                <div class="service-header small-4 end cell">
                    Mileage
                </div>

                <div class="service-header small-4 end cell">
                    Cost
                </div>

            </div>

            <div class="maintenance-items grid-x grid-margin-y" style="position: relative;" id="<%= maintenance.id %>">


                <div class="small-4 cell">
                    <%= maintenance.date_preformed %>
                </div>

                <div class="small-4 cell">
                    <%= maintenance.current_mileage %>
                </div>

                <div class="small-4 cell">
                    <%= maintenance.cost %>
                </div>


                <!-- maintenance delete button -->
                <button class="service close-button" aria-label="Close alert" type="button" id="<%= maintenance.id %>">
                    <span id="<%= @vehicle.id %>" aria-hidden="true">&times;</span>
                </button>

                <!-- maintenance edit button -->
                <button class="service edit-button" type="button" id="<%= maintenance.id %>">
                    <span id="<%= @vehicle.id %>"><i class="fas fa-cogs" aria-hidden="true"></i></i></span>
                </button>



            </div>
        <% end %>
    </div>

    <!----------- button to launch modal to add maintenance --------------->
    <p class="my-p"><a class="button small" href="#serviceModal" rel="modal:open">Add Maintenance</a></p>

    <!----------- Modal to add a new maintenance --------------->
    <%= render 'layouts/new_maintenace_form' %>

</div>